import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "products pages",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
    <header className="p-6 bg-amber-400">Product Header</header>
        <main>{children}</main>
    <footer className="p-6 bg-green-400"> Product Footer</footer>
     </div>
  );
}
